### ISSUE TITLE
Download and unzip tomee

### ISSUE THREAD

**Issue by htmfilho** [bitmaker-software/tomee-cli#16]
(install-tomee "1.7.1" "/path/to/desired/location")

**Comment by danielsoro** [comment]
Maybe `(install-tomee "version" "distribution" "path")`

**Comment by htmfilho** [comment]
I was thinking about:

    (install-tomee :dist "plus" :version "1.7.1" :path "/installation/path")

This way the user can freely change the order:

    (install-tomee :path "/installation/path" :dist "plus" :version "1.7.1")

And we can set optional values for all keys in case of absence:

    (install-tomee) ; install the latest version of the web profile in the current directory
    (install-tomee :dist "plus") ;install the latest version of the plus in the current directory
    ... and so on.

**Comment by danielsoro** [comment]
Include #18
